<?php
/**
 * Contract snapshot diff (task 0.3, gate G5).
 *
 * Compares the runtime recorder output of develop (baseline) with the branch,
 * screen by screen, and lists what the branch lost: handles, dependencies,
 * enqueue state, localized globals and their keys, fired hooks and argument
 * counts. Additions are listed separately and never fail.
 *
 * Usage: php tests/contracts/diff.php <develop-dir> <branch-dir> [--allow=<file>]
 * The allow file lists accepted losses, one "screen<TAB>item" per line (# comments).
 * Exit code 1 when an unaccepted loss is found.
 *
 * @package WP_User_Frontend
 */

if ( 'cli' !== PHP_SAPI ) {
    exit;
}

$wpuf_args  = array_slice( $argv, 1 );
$wpuf_allow = [];

foreach ( $wpuf_args as $wpuf_i => $wpuf_arg ) {
    if ( 0 === strpos( $wpuf_arg, '--allow=' ) ) {
        foreach ( file( substr( $wpuf_arg, 8 ), FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES ) as $wpuf_line ) {
            if ( '#' !== $wpuf_line[0] ) {
                $wpuf_allow[ trim( $wpuf_line ) ] = true;
            }
        }
        unset( $wpuf_args[ $wpuf_i ] );
    }
}

list( $wpuf_base_dir, $wpuf_new_dir ) = array_values( $wpuf_args );

/**
 * Flattens a key tree into "a.b.c" paths.
 *
 * @param mixed  $tree   Tree.
 * @param string $prefix Prefix.
 *
 * @return array
 */
function wpuf_contract_paths( $tree, $prefix = '' ) {
    if ( ! is_array( $tree ) ) {
        return [ $prefix ];
    }

    $out = [];

    foreach ( $tree as $key => $value ) {
        $out = array_merge( $out, wpuf_contract_paths( $value, '' === $prefix ? $key : $prefix . '.' . $key ) );
    }

    return $out ? $out : [ $prefix ];
}

$wpuf_lost  = [];
$wpuf_added = [];

foreach ( glob( $wpuf_base_dir . '/*.json' ) as $wpuf_file ) {
    $wpuf_screen = basename( $wpuf_file, '.json' );
    $wpuf_base   = json_decode( file_get_contents( $wpuf_file ), true );
    $wpuf_path   = $wpuf_new_dir . '/' . $wpuf_screen . '.json';

    if ( ! file_exists( $wpuf_path ) ) {
        $wpuf_lost[] = [ $wpuf_screen, 'screen not recorded on branch' ];
        continue;
    }

    $wpuf_new = json_decode( file_get_contents( $wpuf_path ), true );

    foreach ( [ 'scripts', 'styles' ] as $wpuf_type ) {
        foreach ( $wpuf_base[ $wpuf_type ] as $wpuf_handle => $wpuf_item ) {
            $wpuf_id = $wpuf_type . ' ' . $wpuf_handle;

            if ( ! isset( $wpuf_new[ $wpuf_type ][ $wpuf_handle ] ) ) {
                $wpuf_lost[] = [ $wpuf_screen, $wpuf_id . ' not registered' ];
                continue;
            }

            $wpuf_now = $wpuf_new[ $wpuf_type ][ $wpuf_handle ];

            if ( $wpuf_item['enqueued'] && ! $wpuf_now['enqueued'] ) {
                $wpuf_lost[] = [ $wpuf_screen, $wpuf_id . ' no longer enqueued' ];
            }

            foreach ( array_diff( $wpuf_item['deps'], $wpuf_now['deps'] ) as $wpuf_dep ) {
                $wpuf_lost[] = [ $wpuf_screen, $wpuf_id . ' lost dep ' . $wpuf_dep ];
            }

            foreach ( $wpuf_item['globals'] as $wpuf_global => $wpuf_tree ) {
                $wpuf_new_tree = isset( $wpuf_now['globals'][ $wpuf_global ] ) ? $wpuf_now['globals'][ $wpuf_global ] : null;

                if ( null === $wpuf_new_tree && ! $wpuf_item['enqueued'] ) {
                    continue;
                }

                if ( null === $wpuf_new_tree ) {
                    // The global may have moved to another enqueued handle.
                    foreach ( $wpuf_new[ $wpuf_type ] as $wpuf_other ) {
                        if ( $wpuf_other['enqueued'] && isset( $wpuf_other['globals'][ $wpuf_global ] ) ) {
                            $wpuf_new_tree = $wpuf_other['globals'][ $wpuf_global ];
                            break;
                        }
                    }
                }

                if ( null === $wpuf_new_tree ) {
                    $wpuf_lost[] = [ $wpuf_screen, 'global ' . $wpuf_global . ' missing' ];
                    continue;
                }

                foreach ( array_diff( wpuf_contract_paths( $wpuf_tree ), wpuf_contract_paths( $wpuf_new_tree ) ) as $wpuf_key ) {
                    $wpuf_lost[] = [ $wpuf_screen, 'global ' . $wpuf_global . ' key ' . $wpuf_key ];
                }
            }
        }

        foreach ( array_diff_key( $wpuf_new[ $wpuf_type ], $wpuf_base[ $wpuf_type ] ) as $wpuf_handle => $wpuf_item ) {
            $wpuf_added[] = [ $wpuf_screen, $wpuf_type . ' ' . $wpuf_handle ];
        }
    }

    foreach ( $wpuf_base['hooks'] as $wpuf_hook => $wpuf_meta ) {
        // Option reads generated by WordPress core are not WPUF contracts.
        if ( preg_match( '/^(pre_|default_)?(site_)?(option|transient)_/', $wpuf_hook ) ) {
            continue;
        }

        if ( ! isset( $wpuf_new['hooks'][ $wpuf_hook ] ) ) {
            $wpuf_lost[] = [ $wpuf_screen, 'hook ' . $wpuf_hook . ' not fired' ];
        } elseif ( $wpuf_new['hooks'][ $wpuf_hook ]['args'] < $wpuf_meta['args'] ) {
            $wpuf_lost[] = [ $wpuf_screen, 'hook ' . $wpuf_hook . ' args ' . $wpuf_meta['args'] . ' -> ' . $wpuf_new['hooks'][ $wpuf_hook ]['args'] ];
        }
    }

    foreach ( array_diff_key( $wpuf_new['hooks'], $wpuf_base['hooks'] ) as $wpuf_hook => $wpuf_meta ) {
        $wpuf_added[] = [ $wpuf_screen, 'hook ' . $wpuf_hook ];
    }
}

$wpuf_fail = 0;

echo "## Lost (develop has, branch lacks)\n";
foreach ( $wpuf_lost as $wpuf_row ) {
    $wpuf_ok    = isset( $wpuf_allow[ $wpuf_row[0] . "\t" . $wpuf_row[1] ] ) || isset( $wpuf_allow[ "*\t" . $wpuf_row[1] ] );
    $wpuf_fail += $wpuf_ok ? 0 : 1;
    echo ( $wpuf_ok ? '  allowed ' : '  LOST    ' ) . $wpuf_row[0] . "\t" . $wpuf_row[1] . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}

echo "\n## Added on branch\n";
foreach ( $wpuf_added as $wpuf_row ) {
    echo '  ' . $wpuf_row[0] . "\t" . $wpuf_row[1] . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}

echo "\n" . $wpuf_fail . " unaccepted loss(es)\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
exit( $wpuf_fail ? 1 : 0 );
