/**
 * Tailwind CSS 4 build for the WPUF React admin screens.
 *
 * Kept apart from the frontend's Tailwind 3 toolchain (this package has its own
 * tailwindcss@4). Per screen it writes one stylesheet that looks exactly like
 * the Tailwind 3 one it replaces:
 * - utilities are plain classes (no prefix, like FlyHR) scoped to the screen's
 *   body class with zero specificity (`:where(.wpuf-admin-react) .flex`), so
 *   they never reach other screens or plugins and keep Tailwind 3 strength;
 * - the base layer is the screen's Tailwind 3 base (scoped preflight + forms
 *   base rules, src/base-v3/, generated by gen-v3-base.cjs), because Tailwind
 *   4's reset differs (`* { margin: 0 }`, font stack, forms selectors, order);
 * - cascade layers are flattened, so WordPress admin CSS (unlayered) competes
 *   with these rules by specificity and order, as it did with Tailwind 3.
 *
 * Usage: node build.mjs [entry...]
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import rtlcss from 'rtlcss';

const here = dirname( fileURLToPath( import.meta.url ) );
const plugin = join( here, '..', '..' );

const ENTRIES = {
    settings: {
        input: 'src/settings.css',
        base: 'src/base-v3/settings.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/settings-react.css',
        rtl: false,
    },
};

const compile = async ( css, from ) =>
    ( await postcss( [ tailwind( { base: here, optimize: { minify: true } } ) ] ).process( css, { from } ) ).css;

const skip = ( rule ) => rule.parent && 'atrule' === rule.parent.type && /keyframes/.test( rule.parent.name );

function scopeUtilities( layer, scope ) {
    layer.walkRules( ( rule ) => {
        if ( ! skip( rule ) ) {
            rule.selectors = rule.selectors.map( ( selector ) => `:where(${ scope }) ${ selector.trim() }` );
        }
    } );
}

/**
 * Unwrap every `@layer` (keeping order), drop Tailwind 4's own base layer and
 * put the Tailwind 3 base in its place.
 */
function flatten( css, baseNodes, scope ) {
    const tree = postcss.parse( css );
    const out = postcss.root();
    let based = false;
    const putBase = () => {
        if ( ! based ) {
            baseNodes.forEach( ( node ) => out.append( node.clone() ) );
            based = true;
        }
    };

    tree.each( ( node ) => {
        if ( 'atrule' !== node.type || 'layer' !== node.name ) {
            out.append( node.clone() );
            return;
        }
        if ( ! node.nodes ) {
            return; // `@layer a, b;` order statement.
        }
        if ( 'base' === node.params ) {
            putBase();
            return;
        }
        if ( 'utilities' === node.params ) {
            putBase();
            scopeUtilities( node, scope );
        }
        node.each( ( child ) => out.append( child.clone() ) );
    } );

    putBase();

    return out.toResult( { map: false } ).css;
}

async function build( name ) {
    const entry = ENTRIES[ name ];

    if ( ! entry ) {
        throw new Error( `Unknown entry "${ name }": ${ Object.keys( ENTRIES ).join( ', ' ) }` );
    }

    const from = join( here, entry.input );
    const baseFrom = join( here, entry.base );
    const css = await compile( await readFile( from, 'utf8' ), from );
    const base = postcss.parse( await compile( await readFile( baseFrom, 'utf8' ), baseFrom ) ).nodes;
    const result = flatten( css, base, entry.scope );
    const target = join( plugin, entry.output );

    await mkdir( dirname( target ), { recursive: true } );
    await writeFile( target, result );

    if ( entry.rtl ) {
        await writeFile( target.replace( /\.css$/, '-rtl.css' ), rtlcss.process( result ) );
    }

    console.log( `admin-css: ${ name } -> ${ relative( plugin, target ) } (${ Math.round( result.length / 1024 ) } KB)` );
}

const names = process.argv.slice( 2 );

for ( const name of names.length ? names : Object.keys( ENTRIES ) ) {
    await build( name );
}
