/**
 * Tailwind CSS 4 build for the WPUF React admin screens.
 *
 * Kept apart from the frontend's Tailwind 3 toolchain (this package has its own
 * tailwindcss@4). Per screen it writes one stylesheet that looks exactly like
 * the Tailwind 3 one it replaces:
 * - utilities are plain classes (no prefix, like FlyHR) scoped to the screen's
 *   body class with zero specificity (`:where(.wpuf-admin-react) .flex`), so
 *   they never reach other screens or plugins and keep Tailwind 3 strength;
 * - everything else comes from the screen's former Tailwind 3 stylesheet
 *   (src/base-v3/<screen>.pre.css: scoped preflight, forms base, components;
 *   .post.css: rules written after the utilities; generated by
 *   gen-v3-base.cjs), because Tailwind 4's reset and daisyUI 5 differ;
 * - cascade layers are flattened, so WordPress admin CSS (unlayered) competes
 *   with these rules by specificity and order, as it did with Tailwind 3.
 *
 * Usage: node build.mjs [entry...]
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import rtlcss from 'rtlcss';

const here = dirname( fileURLToPath( import.meta.url ) );
const plugin = join( here, '..', '..' );

const ENTRIES = {
    settings: {
        input: 'src/settings.css',
        pre: 'src/base-v3/settings.pre.css',
        post: 'src/base-v3/settings.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/settings-react.css',
        rtl: false,
    },
    subscriptions: {
        input: 'src/subscriptions.css',
        pre: 'src/base-v3/subscriptions.pre.css',
        post: 'src/base-v3/subscriptions.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/subscriptions.css',
        rtl: true,
    },
    forms: {
        input: 'src/forms.css',
        pre: 'src/base-v3/forms.pre.css',
        post: 'src/base-v3/forms.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/admin/forms-react.css',
        rtl: false,
    },
};

const compile = async ( css, from ) =>
    ( await postcss( [ tailwind( { base: here, optimize: { minify: true } } ) ] ).process( css, { from } ) ).css;

const skip = ( rule ) => rule.parent && 'atrule' === rule.parent.type && /keyframes/.test( rule.parent.name );

function scopeUtilities( layer, scope ) {
    layer.walkRules( ( rule ) => {
        if ( ! skip( rule ) ) {
            rule.selectors = rule.selectors.map( ( selector ) => `:where(${ scope }) ${ selector.trim() }` );
        }
    } );
}

/**
 * Unwrap every `@layer` (keeping order), drop Tailwind 4's own base layer and
 * put the Tailwind 3 base in its place.
 */
/**
 * Rendering details pinned to Tailwind 3: `rounded-full` is 9999px (Tailwind 4:
 * calc(infinity * 1px), which anti-aliases curved edges differently), colors
 * with an opacity modifier keep the hex + alpha value (Tailwind 4 adds an
 * `@supports (color-mix)` override mixing in oklab) and gradients interpolate
 * in sRGB.
 */
function pinV3Rendering( tree ) {
    tree.walkAtRules( 'supports', ( rule ) => {
        if ( /color-mix/.test( rule.params ) ) {
            rule.remove();
        }
    } );
    tree.walkDecls( ( decl ) => {
        if ( /^border(-[a-z]+)*-radius$/.test( decl.prop ) && /3\.40282e38px|calc\(infinity/.test( decl.value ) ) {
            decl.value = '9999px';
        }
        // Gradients interpolate in sRGB as in Tailwind 3 (Tailwind 4: `in oklab`).
        if ( '--tw-gradient-position' === decl.prop ) {
            decl.value = decl.value.replace( /\s+in\s+oklab/, '' );
        }
    } );
}

function flatten( css, baseNodes, postNodes, scope ) {
    const tree = postcss.parse( css );
    pinV3Rendering( tree );
    const out = postcss.root();
    let based = false;
    const putBase = () => {
        if ( ! based ) {
            baseNodes.forEach( ( node ) => out.append( node.clone() ) );
            based = true;
        }
    };

    tree.each( ( node ) => {
        if ( 'atrule' !== node.type || 'layer' !== node.name ) {
            out.append( node.clone() );
            return;
        }
        if ( ! node.nodes ) {
            return; // `@layer a, b;` order statement.
        }
        if ( 'base' === node.params ) {
            putBase();
            return;
        }
        if ( 'utilities' === node.params ) {
            putBase();
            scopeUtilities( node, scope );
            node.each( ( child ) => out.append( child.clone() ) );
            postNodes.forEach( ( child ) => out.append( child.clone() ) );
            postNodes = [];
            return;
        }
        node.each( ( child ) => out.append( child.clone() ) );
    } );

    putBase();
    postNodes.forEach( ( node ) => out.append( node.clone() ) );

    // Tailwind 3: text-* sets line-height outright, so whichever of text-* /
    // leading-* comes later in the cascade wins (`leading-none sm:text-sm` gets
    // the sm line height). Tailwind 4 writes var(--tw-leading, …) instead.
    return out
        .toResult( { map: false } )
        .css.replace( /line-height:\s*var\(--tw-leading,\s*var\((--text-[\w-]+--line-height)\)\)/g, 'line-height:var($1)' );
}

async function build( name ) {
    const entry = ENTRIES[ name ];

    if ( ! entry ) {
        throw new Error( `Unknown entry "${ name }": ${ Object.keys( ENTRIES ).join( ', ' ) }` );
    }

    const from = join( here, entry.input );
    const part = async ( file ) => {
        const tree = postcss.parse( await compile( await readFile( join( here, file ), 'utf8' ), join( here, file ) ) );
        tree.walkComments( ( comment ) => comment.remove() );
        return tree.nodes;
    };
    const css = await compile( await readFile( from, 'utf8' ), from );
    const result = flatten( css, await part( entry.pre ), await part( entry.post ), entry.scope );
    const target = join( plugin, entry.output );

    await mkdir( dirname( target ), { recursive: true } );
    await writeFile( target, result );

    if ( entry.rtl ) {
        await writeFile( target.replace( /\.css$/, '-rtl.css' ), rtlcss.process( result ) );
    }

    console.log( `admin-css: ${ name } -> ${ relative( plugin, target ) } (${ Math.round( result.length / 1024 ) } KB)` );
}

const names = process.argv.slice( 2 );

for ( const name of names.length ? names : Object.keys( ENTRIES ) ) {
    await build( name );
}
