/**
 * Tailwind CSS 4 build for the WPUF React admin screens.
 *
 * Kept apart from the frontend's Tailwind 3 toolchain (this package has its own
 * tailwindcss@4). Per screen it writes one stylesheet that looks exactly like
 * the Tailwind 3 one it replaces:
 * - utilities are plain classes (no prefix, like FlyHR) scoped to the screen's
 *   body class with zero specificity (`:where(.wpuf-admin-react) .flex`), so
 *   they never reach other screens or plugins and keep Tailwind 3 strength;
 * - everything else comes from the screen's former Tailwind 3 stylesheet
 *   (src/base-v3/<screen>.pre.css: scoped preflight, forms base, components;
 *   .post.css: rules written after the utilities; generated by
 *   gen-v3-base.cjs), because Tailwind 4's reset and daisyUI 5 differ;
 * - cascade layers are flattened, so WordPress admin CSS (unlayered) competes
 *   with these rules by specificity and order, as it did with Tailwind 3;
 * - a screen with `pui: true` also gets the plugin-ui part (src/pui.css,
 *   see puiPart()) at the top of the same file, and with `dataviews: true` the DataViews
 *   styles (src/pui-dataviews.css).
 *
 * Usage: node build.mjs [entry...]
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
import rtlcss from 'rtlcss';

const here = dirname( fileURLToPath( import.meta.url ) );
const plugin = join( here, '..', '..' );

const ENTRIES = {
    settings: {
        input: 'src/settings.css',
        pre: 'src/base-v3/settings.pre.css',
        post: 'src/base-v3/settings.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/settings-react.css',
        rtl: false,
    },
    subscriptions: {
        input: 'src/subscriptions.css',
        pre: 'src/base-v3/subscriptions.pre.css',
        post: 'src/base-v3/subscriptions.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/subscriptions.css',
        rtl: true,
        // Shared wrappers since 4.1a (plugin-ui part, page background).
        pui: true,
    },
    forms: {
        input: 'src/forms.css',
        pre: 'src/base-v3/forms.pre.css',
        post: 'src/base-v3/forms.post.css',
        scope: '.wpuf-admin-react',
        output: 'assets/css/admin/forms-react.css',
        rtl: false,
    },
};

const compile = async ( css, from ) =>
    ( await postcss( [ tailwind( { base: here, optimize: { minify: true } } ) ] ).process( css, { from } ) ).css;

const skip = ( rule ) => rule.parent && 'atrule' === rule.parent.type && /keyframes/.test( rule.parent.name );

function scopeUtilities( layer, scope ) {
    layer.walkRules( ( rule ) => {
        if ( ! skip( rule ) ) {
            rule.selectors = rule.selectors.map( ( selector ) => `:where(${ scope }) ${ selector.trim() }` );
        }
    } );
}

/**
 * Unwrap every `@layer` (keeping order), drop Tailwind 4's own base layer and
 * put the Tailwind 3 base in its place.
 */
/**
 * Rendering details pinned to Tailwind 3: `rounded-full` is 9999px (Tailwind 4:
 * calc(infinity * 1px), which anti-aliases curved edges differently), colors
 * with an opacity modifier keep the hex + alpha value (Tailwind 4 adds an
 * `@supports (color-mix)` override mixing in oklab) and gradients interpolate
 * in sRGB.
 */
function pinV3Rendering( tree ) {
    tree.walkAtRules( 'supports', ( rule ) => {
        if ( /color-mix/.test( rule.params ) ) {
            rule.remove();
        }
    } );
    tree.walkDecls( ( decl ) => {
        if ( /^border(-[a-z]+)*-radius$/.test( decl.prop ) && /3\.40282e38px|calc\(infinity/.test( decl.value ) ) {
            decl.value = '9999px';
        }
        // Gradients interpolate in sRGB as in Tailwind 3 (Tailwind 4: `in oklab`).
        if ( '--tw-gradient-position' === decl.prop ) {
            decl.value = decl.value.replace( /\s+in\s+oklab/, '' );
        }
    } );
}

function flatten( css, baseNodes, postNodes, scope ) {
    const tree = postcss.parse( css );
    pinV3Rendering( tree );
    const out = postcss.root();
    let based = false;
    const putBase = () => {
        if ( ! based ) {
            baseNodes.forEach( ( node ) => out.append( node.clone() ) );
            based = true;
        }
    };

    tree.each( ( node ) => {
        if ( 'atrule' !== node.type || 'layer' !== node.name ) {
            out.append( node.clone() );
            return;
        }
        if ( ! node.nodes ) {
            return; // `@layer a, b;` order statement.
        }
        if ( 'base' === node.params ) {
            putBase();
            return;
        }
        if ( 'utilities' === node.params ) {
            putBase();
            scopeUtilities( node, scope );
            node.each( ( child ) => out.append( child.clone() ) );
            postNodes.forEach( ( child ) => out.append( child.clone() ) );
            postNodes = [];
            return;
        }
        node.each( ( child ) => out.append( child.clone() ) );
    } );

    putBase();
    postNodes.forEach( ( node ) => out.append( node.clone() ) );

    // Tailwind 3: text-* sets line-height outright, so whichever of text-* /
    // leading-* comes later in the cascade wins (`leading-none sm:text-sm` gets
    // the sm line height). Tailwind 4 writes var(--tw-leading, …) instead.
    return out
        .toResult( { map: false } )
        .css.replace( /line-height:\s*var\(--tw-leading,\s*var\((--text-[\w-]+--line-height)\)\)/g, 'line-height:var($1)' );
}

/**
 * The plugin-ui part (src/pui.css) for a screen with `pui: true`: its theme
 * variables move from :root to `.pui-root` (the screen's own Tailwind 3
 * values stay on :root), its utilities (`!important`) apply to `.pui-root`
 * and everything inside it (portals included), its preflight stays nested
 * under `.pui-root`. Cascade layers are flattened like the screen part.
 */
// The WordPress editor (TinyMCE + Quicktags, WpEditor) keeps WordPress's own
// look inside plugin-ui screens: plugin-ui's preflight, base and form resets
// skip `.wp-editor-wrap` (zero added specificity; utilities still apply).
const WP_EDITOR_SKIP = ':where(:not(.wp-editor-wrap, .wp-editor-wrap *))';

// Appends a zero-specificity condition to a selector's subject, before any
// pseudo-element.
function addCondition( selector, condition ) {
    if ( selector.includes( condition ) ) {
        return selector;
    }
    const at = selector.indexOf( '::' );

    return -1 === at ? selector + condition : selector.slice( 0, at ) + condition + selector.slice( at );
}

function skipWpEditor( selector ) {
    return /\.pui-root[\s>~+]/.test( selector ) ? addCondition( selector, WP_EDITOR_SKIP ) : selector;
}

// Legacy host (design.md D25): a screen still being migrated renders
// WpufProviders with `host`, so its ThemeProvider root gets `.wpuf-pui-host`.
// Inside it, plugin-ui styles reach only plugin-ui parts (`[data-slot]`),
// wrapper roots (`[data-wpuf-ui]`) and what is inside them; the screen's own
// markup keeps its look. Outside a host (portals, fully migrated screens)
// nothing changes.
const HOST = '.wpuf-pui-host';
const ISLAND = `:where(:not(${ HOST } *), [data-slot], [data-slot] *, [data-wpuf-ui], [data-wpuf-ui] *)`;

function island( selector ) {
    return /\.pui-root/.test( selector ) ? addCondition( selector, ISLAND ) : selector;
}

// Base rules on the root itself (font, color, line-height) do not apply to a
// host root, so they do not leak into its legacy markup by inheritance.
function rootBase( rule ) {
    const onlyVariables = rule.nodes.every( ( node ) => 'decl' !== node.type || node.prop.startsWith( '--' ) );

    if ( ! onlyVariables ) {
        rule.selectors = rule.selectors.map( ( selector ) => ( '.pui-root' === selector.trim() ? `.pui-root:not(${ HOST })` : selector ) );
    }
}

async function puiPart() {
    const from = join( here, 'src/pui.css' );
    const tree = postcss.parse( await compile( await readFile( from, 'utf8' ), from ) );
    const out = [];

    tree.walkComments( ( comment ) => comment.remove() );
    tree.each( ( node ) => {
        if ( 'atrule' !== node.type || 'layer' !== node.name ) {
            out.push( node.clone() );
            return;
        }
        if ( ! node.nodes ) {
            return;
        }
        if ( 'theme' === node.params ) {
            node.walkRules( ( rule ) => {
                rule.selectors = rule.selectors.map( ( selector ) => ( /^(:root|:host)$/.test( selector.trim() ) ? '.pui-root' : selector ) );
                rule.selectors = [ ...new Set( rule.selectors ) ];
            } );
        }
        if ( 'utilities' === node.params ) {
            node.walkRules( ( rule ) => {
                if ( skip( rule ) ) {
                    return;
                }
                rule.selectors = rule.selectors.flatMap( ( selector ) => {
                    const trimmed = selector.trim();
                    // `.pui-root .x` and the root itself (`.pui-root.x`).
                    return trimmed.startsWith( '.' )
                        ? [ `:where(.pui-root) ${ trimmed }`, `:where(.pui-root)${ trimmed }` ]
                        : [ `:where(.pui-root) ${ trimmed }` ];
                } ).map( island );
            } );
        }
        if ( 'theme' !== node.params && 'utilities' !== node.params ) {
            node.walkRules( ( rule ) => {
                rootBase( rule );
                rule.selectors = rule.selectors.map( skipWpEditor ).map( island );
            } );
        }
        node.each( ( child ) => out.push( child.clone() ) );
    } );

    // Unlayered rules of pui.css (WordPress forms.css resets).
    out.forEach( ( node ) => {
        if ( 'rule' === node.type ) {
            rootBase( node );
            node.selectors = node.selectors.map( skipWpEditor ).map( island );
        }
    } );

    return out;
}

async function build( name ) {
    const entry = ENTRIES[ name ];

    if ( ! entry ) {
        throw new Error( `Unknown entry "${ name }": ${ Object.keys( ENTRIES ).join( ', ' ) }` );
    }

    const from = join( here, entry.input );
    const part = async ( file ) => {
        const tree = postcss.parse( await compile( await readFile( join( here, file ), 'utf8' ), join( here, file ) ) );
        tree.walkComments( ( comment ) => comment.remove() );
        return tree.nodes;
    };
    const css = await compile( await readFile( from, 'utf8' ), from );
    let result = flatten( css, await part( entry.pre ), await part( entry.post ), entry.scope );

    if ( entry.pui ) {
        const pui = postcss.root();
        ( await puiPart() ).forEach( ( node ) => pui.append( node ) );
        // First in the file: with equal specificity the screen's own utilities
        // (classes a screen passes to a wrapper) then win over the plugin-ui
        // preflight, while plugin-ui's !important utilities still win.
        result = pui.toResult( { map: false } ).css + result;
    }

    // DataViews styles (generated src/pui-dataviews.css) for screens that list with it.
    if ( entry.dataviews ) {
        result += ( await compile( await readFile( join( here, 'src/pui-dataviews.css' ), 'utf8' ), join( here, 'src/pui-dataviews.css' ) ) );
    }
    const target = join( plugin, entry.output );

    await mkdir( dirname( target ), { recursive: true } );
    await writeFile( target, result );

    if ( entry.rtl ) {
        await writeFile( target.replace( /\.css$/, '-rtl.css' ), rtlcss.process( result ) );
    }

    console.log( `admin-css: ${ name } -> ${ relative( plugin, target ) } (${ Math.round( result.length / 1024 ) } KB)` );
}

const names = process.argv.slice( 2 );

for ( const name of names.length ? names : Object.keys( ENTRIES ) ) {
    await build( name );
}
