/**
 * Regenerates src/base-v3/<screen>.css: each React screen's Tailwind 3 base
 * layer (scoped preflight + @tailwindcss/forms base rules) exactly as its
 * Tailwind 3 config produced it (same plugins, same order, same scope). The
 * Tailwind 4 admin build uses it instead of the Tailwind 4 base, so the
 * screens keep the exact look they had.
 *
 * Run from the plugin root (uses the frontend's tailwindcss@3):
 *   node tools/admin-css/gen-v3-base.cjs
 */
const fs = require( 'fs' );
const path = require( 'path' );
// The plugin root's packages (tailwindcss@3), not this package's Tailwind 4.
const rootRequire = require( 'module' ).createRequire( path.join( __dirname, '..', '..', 'package.json' ) );
const postcss = rootRequire( 'postcss' );
const tailwind = rootRequire( 'tailwindcss' );
const forms = rootRequire( '@tailwindcss/forms' );
const { scopedPreflightStyles, isolateInsideOfContainer } = rootRequire( 'tailwindcss-scoped-preflight' );

const out = path.join( __dirname, 'src', 'base-v3' );
const scoped = ( roots ) => scopedPreflightStyles( { isolationStrategy: isolateInsideOfContainer( roots, {} ) } );

// Same plugin list and order as the screen's former Tailwind 3 config.
const variants = {
    // tailwind.settings.config.js
    settings: [ forms( { strategy: 'base' } ), scoped( [ '#wpuf-settings-root' ] ) ],
};

fs.mkdirSync( out, { recursive: true } );

( async () => {
    for ( const [ name, plugins ] of Object.entries( variants ) ) {
        const result = await postcss( [ tailwind( { content: [ { raw: '<div></div>' } ], plugins } ) ] ).process( '@tailwind base;', { from: undefined } );
        const head = `/* Tailwind CSS 3 base layer (${ name }), generated by gen-v3-base.cjs. Do not edit. */\n`;
        fs.writeFileSync( path.join( out, `${ name }.css` ), head + result.css.trim() + '\n' );
        console.log( name, result.css.length );
    }
} )();
