/**
 * Regenerates src/base-v3/<screen>.pre.css and .post.css: everything a React
 * screen's former Tailwind 3 stylesheet held except its utilities, exactly as
 * that config produced it (same plugins, order, scope, content):
 * - .pre.css: base layer (scoped preflight, forms base) + components layer
 *   (daisyUI and the stylesheet's own `@layer components` rules);
 * - .post.css: the stylesheet's unlayered rules written after the utilities.
 * The Tailwind 4 admin build puts them around its utilities, so the screens
 * keep the exact look they had. Component class names keep their `wpuf-`
 * names (pro modules and third-party markup use them).
 *
 * Run from anywhere (uses the plugin root's tailwindcss@3):
 *   node tools/admin-css/gen-v3-base.cjs
 */
const fs = require( 'fs' );
const path = require( 'path' );

const root = path.join( __dirname, '..', '..' );
// The plugin root's packages (tailwindcss@3), not this package's Tailwind 4.
const rootRequire = require( 'module' ).createRequire( path.join( root, 'package.json' ) );
const postcss = rootRequire( 'postcss' );
const tailwind = rootRequire( 'tailwindcss' );
const forms = rootRequire( '@tailwindcss/forms' );
const { scopedPreflightStyles, isolateInsideOfContainer } = rootRequire( 'tailwindcss-scoped-preflight' );

const out = path.join( __dirname, 'src', 'base-v3' );
const MARK = '/*! wpuf-utilities */';
const directives = `@tailwind base;\n@tailwind components;\n${ MARK }\n`;

const variants = {
    // Former tailwind.settings.config.js (its custom rules live in src/settings.css).
    settings: {
        config: {
            prefix: 'wpuf-',
            content: [ { raw: '' } ],
            plugins: [
                forms( { strategy: 'base' } ),
                scopedPreflightStyles( { isolationStrategy: isolateInsideOfContainer( [ '#wpuf-settings-root' ], {} ) } ),
            ],
        },
        input: directives,
    },
    // Shared tailwind.config.js + src/css/subscriptions.css (webpack import).
    subscriptions: {
        config: 'tailwind.config.js',
        input: directives,
    },
};

fs.mkdirSync( out, { recursive: true } );

( async () => {
    process.chdir( root ); // Content globs in the configs are relative to the plugin root.

    for ( const [ name, variant ] of Object.entries( variants ) ) {
        const config = 'string' === typeof variant.config ? rootRequire( path.join( root, variant.config ) ) : variant.config;
        const result = await postcss( [ tailwind( config ) ] ).process( variant.input, { from: undefined } );
        const [ pre, post = '' ] = result.css.split( MARK );
        const head = ( part ) => `/* Tailwind CSS 3 ${ part } of the ${ name } screen, generated by gen-v3-base.cjs. Do not edit. */\n`;

        fs.writeFileSync( path.join( out, `${ name }.pre.css` ), head( 'base + components' ) + pre.trim() + '\n' );
        fs.writeFileSync( path.join( out, `${ name }.post.css` ), head( 'rules after the utilities' ) + post.trim() + '\n' );
        console.log( name, pre.length, post.length );
    }
} )();
