/**
 * Regenerates src/pui-upstream.css from @wedevs/plugin-ui's own
 * src/styles.css (the pinned package): default tokens on `.pui-root`, the
 * `@theme inline` mapping (colors, radius, shadows), the scoped base and its
 * helper rules, tw-animate-css, and the scoped `.pui-root-dataviews` rules.
 * Left out, because they would style the whole admin page:
 * - `@import "tailwindcss"` (global preflight + utilities; src/pui.css
 *   builds scoped ones);
 * - the global @wordpress/components, @wordpress/dataviews and
 *   @wordpress/theme stylesheets (wp-components style handle; DataViews
 *   wrapper, task 3.3d).
 *
 * Run after moving the plugin-ui pin: node tools/admin-css/gen-pui.cjs
 */
const fs = require( 'fs' );
const path = require( 'path' );

const root = path.join( __dirname, '..', '..' );
const pkg = fs.realpathSync( path.join( root, 'node_modules', '@wedevs', 'plugin-ui' ) );
const src = path.join( pkg, 'src' );
const sha = ( JSON.parse( fs.readFileSync( path.join( root, 'package.json' ), 'utf8' ) ).dependencies[ '@wedevs/plugin-ui' ] || '' ).split( '#' ).pop();

const wordpress = fs
    .readFileSync( path.join( src, 'components', 'wordpress', 'style.css' ), 'utf8' )
    .replace( /^@import\s+['"]@wordpress\/[^'"]+['"];\s*$/gm, '' )
    .trim();

let css = fs.readFileSync( path.join( src, 'styles.css' ), 'utf8' );
const before = css;

css = css.replace( /^@import\s+["']tailwindcss["'][^;]*;\s*$/m, '' );
css = css.replace( /^@import\s+["']\.\/components\/wordpress\/style\.css["'];\s*$/m, () => wordpress + '\n' );

if ( css === before || /@import\s+["']tailwindcss["']/.test( css ) || /@wordpress\/(components|dataviews|theme)\//.test( css ) ) {
    throw new Error( 'plugin-ui src/styles.css changed shape: update gen-pui.cjs.' );
}

const head = `/* Generated by gen-pui.cjs from @wedevs/plugin-ui src/styles.css (${ sha }). Do not edit. */\n`;

fs.writeFileSync( path.join( __dirname, 'src', 'pui-upstream.css' ), head + css.trim() + '\n' );
console.log( 'pui-upstream.css', css.length );
